[package]
name = "ray-tracing"
version = "0.1.0"
authors = ["Thomas van Lankveld <tvlankveld@smart-robotics.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conv = "0.3.3"
rand = "0.8.2"
